---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-operator

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: redis-operator
subjects:
- kind: ServiceAccount
  name: redis-operator
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-operator-init
data:
  init.sh: |
    helm-app-operator --init && helm-app-operator --install-once=redis && \
    rm -fr chart && helm fetch stable/redis --untar && mv redis chart

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-operator
  template:
    metadata:
      labels:
        app: redis-operator
    spec:
      serviceAccountName: redis-operator
      containers:
        - name: operator
          image: xiaopal/helm-app-operator
          env:
            - name: CRD_RESOURCE
              value: RedisApp,redisapps.xiaopal.github.com/v1beta1
            - name: HELM_CHART
              value: /chart
            - name: OPERATOR_NAME
              valueFrom: {fieldRef: {fieldPath: 'metadata.labels["app"]'}}
          volumeMounts:
            - mountPath: /etc/entrypoint.d
              name: entrypoint-init
      volumes:
        - name: entrypoint-init
          configMap: {name: redis-operator-init}

